image: nginx:1.24-alpine
replicaCount: 2
service:
  name: simple-nginx
  port: 8080

resources:
  requests:
    memory: "32Mi"
    cpu: "10m"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCpu: 80
